### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by peter-rs** [paradoxwastaken/Poseidon#11]
Is it supposed to be very slow to read memory? Takes me about 3 seconds to read 64 addresses.

**Comment by rgbrax** [comment]
^^^ If anybody finds the issue do let me know

**Comment by peter-rs** [comment]
> ^^^ If anybody finds the issue do let me know
Are you using a KProcess object or direct read?

**Comment by rgbrax** [comment]
> ^^^ If anybody finds the issue do let me know
> Are you using a KProcess object or direct read?

Sorry for the late reply. I’ve completely deleted the Kprocess class I only use direct read. Have you found one to be quicker?

there’s a couple sleeps in the switch routine for the driver loop but those are mostly for routines where the driver is inactive and even removing them just to be sure did no help. It may just be the hook itself. 

Note: mine is a 32bit process. It’s just slow enough to shoot right after I cross over somebody’s body on the Triggerbot I’ve made.

**Comment by peter-rs** [comment]
I was just wondering as I thought the KProcess might be slower, however they appear to be the same speed. Looping through entity list in CS:Go gets me 1 frame every 3 seconds of ESP. 

> > ^^^ If anybody finds the issue do let me know
> > Are you using a KProcess object or direct read?
> 
> Sorry for the late reply. I’ve completely deleted the Kprocess class I only use direct read. Have you found one to be quicker?
> 
> there’s a couple sleeps in the switch routine for the driver loop but those are mostly for routines where the driver is inactive and even removing them just to be sure did no help. It may just be the hook itself.
> 
> Note: mine is a 32bit process. It’s just slow enough to shoot right after I cross over somebody’s body on the Triggerbot I’ve made.

**Comment by ghost** [comment]
Hey, did you manage what is the performance bottleneck? I really consider if it is not the MmCopyVirtualMemory itself? Every call internally attaches to the process so maybe this is slow?

**Comment by peter-rs** [comment]
> Hey, did you manage what is the performance bottleneck? I really consider if it is not the MmCopyVirtualMemory itself? Every call internally attaches to the process so maybe this is slow?

I believe it has more to do with the communication method than the actual copying code. I don't believe there's anyway to resolve this issue other than implementing an entirely different communication method. Perhaps something from here should help guide: https://github.com/adspro15/km-um-communication

**Comment by xxTree** [comment]
> > ^^^ 如果有人发现问题，请告诉我
> > 您是使用 KProcess 对象还是直接读取？
> 
> 这么晚才回复很抱歉。我已经完全删除了我只使用直接读取的 Kprocess 类。你有没有发现一个更快？
> 
> 在驱动程序循环的开关例程中有几个睡眠，但这些主要用于驱动程序处于非活动状态的例程，甚至删除它们只是为了确保没有帮助。它可能只是钩子本身。
> 
> 注意：我的是一个 32 位进程。在我制作的 Triggerbot 上越过某人的身体后，它的速度足以立即射击。

hello~Please tell me how to synchronize. I update the shared memory in the driver layer. If sleep() is not used, the shared memory in the application layer will not be updated. Thank you

**Comment by TobiasStaack** [comment]
there is a way to make it fast enough, just create more memory pools and remove 99% of the used sleeps, because if u sum them up u will notice a big delay between the requesting and response, also use 2 different memory pools, one for the request and the other one for the response.

**Comment by AIVDNL** [comment]
single call takes 40 ms even after removing all sleeps. Anyone who has a reference implementation that is faster so I can get a better understanding why exactly it is so slow?

**Comment by TobiasStaack** [comment]
Add me on Discord MYLIFEISMYHOME#0728 I will hand u mine

**Comment by AIVDNL** [comment]
Added you (AIVDNL#4767)
