### ISSUE TITLE
For those wondering about detection (vectors)

### ISSUE THREAD

**Issue by RutgerVersteegden** [paradoxwastaken/Poseidon#18]
This is detected both on EAC / BE as of right now. 

Someone correct me if I'm wrong but I don't think this was ever undetected, at least not on BattlEye. They can simply stack-walk (query an APC) on your thread called in usermode (they have been doing so for a long time)
and see that it is executing in an illegal memory region (i.e not backed by a valid kernel module). 

EAC uses (as of recently) NMI callbacks which will find the thread

for BE there is an obvious fix publicly available (disable APCs), for EAC not so much, at least not that I know of.

Note that mapping this using kdmapper without any other precautions is also detected. EAC scans all BigPools / walks PTEs.
Also the MMcopyMemory can be (maybe is) hooked by BE/EAC.

**Comment by sondernextdoor** [comment]
> They can simply stack-walk (query an APC) on your thread called in usermode (they have been doing so for a long time)

Correct, but I don't believe this is a reliable enough vector on its own to result in any significant action. I can confirm that even while allowing APCs to be queued, BE wasn't banning for the sole use of this as of a few months ago. A straight-forward solution to eliminate this vector is to simply flip the APCQueueable flag.

> EAC uses (as of recently) NMI callbacks which will find the thread

Correct again. This project was developed prior to the implementation of their NMI callback heuristic and I'm honestly not sure of any way around this one. In terms of the reliability of this vector, it's probably the same as above (i.e. not reliable enough to take any significant action). Can confirm EAC was not banning for the sole use of this as of a few months ago.

> Also the MMcopyMemory can be (maybe is) hooked by BE/EAC.

As far as I'm aware, they cannot hook any kernel routine (doing so would eventually trigger KPP). Boot-start drivers could potentially install IAT hooks, but that's not applicable in this case. KeStackAttachProcess can be detected in a multitude of ways, so using alternative methods (e.g. physical memory for r/w operations) when necessary to avoid that routine (or any routine that calls it) is advised.

This project was never really meant to be fully UD without some tweaks, especially for any blatant illicit use (e.g. aimbots and ESPs). I, and everyone I know who used it, haven't had any issues using it for non-illicit (or relatively tame) purposes.
