### ISSUE TITLE
KMode Exception BSOD

### ISSUE THREAD

**Issue by TibblesGH** [paradoxwastaken/Poseidon#2]
Probably utilizing this wrong:

Getting BSOD for KMode Exception Not Handled when calling ::Connect() in client code. Built both Driver.sys & Client and manually mapped Driver.sys using kdmapper. Output from KDMapper appears valid and that driver is mapped.

Any recommended mapping tool or method? Running Windows 10 19041

**Comment by sondernextdoor** [comment]
remove/comment out ```System::ClearPiDDBCache(L"iqvw64e.sys", gKernelBase);``` in Poseidon/sdk.h and see if that resolves the issue.
