### ISSUE TITLE
how to read ++ adress

### ISSUE THREAD

**Issue by smef153** [paradoxwastaken/Poseidon#6]
ok so i was tryna get some things going and im trying to figure out if im doing it right
	KProcess Notepad(L"UnityPlayer.dll");
	int ObjMgr = Notepad.Read<int>((PVOID)0x17A6AD8);
now im hoping the above function is reading UnityPlayer.dll +  0x17A6AD8
now if the above function works then ObjMgr Will = UnityPlayer.dll +  0x17A6AD8
but i dont know how to then read ObjMgr 0x08
so the output will be UnityPlayer.dll + 0x17A6AD8 + 0x08

i tried this but it didnt seem to work
	KProcess Notepad(L"UnityPlayer.dll");
	int ObjMgr = Notepad.Read<int>((PVOID)0x17A6AD8);
	int Obj = Notepad.Read<int>((int)0x08);
any help would be appreciated :D

**Comment by smef153** [comment]
UINT64 Obj = Notepad.Read<int>((PVOID)ObjMgr, 0x08); 
i tried this i doesnt throw out errors still not sure if it will function

**Comment by raywave** [comment]
`KProcess Notepad(L"UnityPlayer.dll");` is searching for proccess called `UnitPlayer.dll`, you need to find module base address in proccess you want, `Notepad.exe`, for example. After you found base address of module, add 0x17A6AD8 to found base.

**Comment by smef153** [comment]
unityPlayer.dll is the process i want to search

**Comment by raywave** [comment]
> unityPlayer.dll is the process i want to search

unityPlayer.dll can't be a proccess, it's a module in process, for example, RustClient.exe or EscapeFromTarkov.exe

**Comment by smef153** [comment]
i see, so how do i rpm inside UnityPlayer.dll
